import { ITransactionItem } from "./types";

export const mockHistory: ITransactionItem[] = [
  {
    id: "1",
    merchant: "Starbucks",
    amount: -4.99,
    date: 23456236,
    category: "food",
    paymentMethod: "Credit Card",
    notes: "Morning coffee with Sarah",
  },
  {
    id: "2",
    merchant: "Amazon",
    amount: -89.99,
    date: 234623456,
    category: "shopping",
    paymentMethod: "Credit Card",
    notes: "New headphones",
  },
  {
    id: "3",
    merchant: "Uber",
    amount: -24.5,
    date: 123451435,
    category: "transport",
    paymentMethod: "Debit Card",
    notes: "Trip to dinner",
  },
  {
    id: "4",
    merchant: "Netflix",
    amount: -15.99,
    date: 12341234,
    category: "entertainment",
    paymentMethod: "Automatic Payment",
    notes: "Monthly subscription",
  },
  {
    id: "5",
    merchant: "Salary Deposit",
    amount: 3500.0,
    date: 142341234,
    category: "income",
    paymentMethod: "Direct Deposit",
    notes: "February salary",
  },
  {
    id: "6",
    merchant: "Electric Company",
    amount: -85.32,
    date: 2345234562345,
    category: "utilities",
    paymentMethod: "Automatic Payment",
    notes: "Monthly electricity bill",
  },
  {
    id: "7",
    merchant: "Venmo",
    amount: 28.5,
    date: 1234,
    category: "transfer",
    paymentMethod: "Venmo",
    notes: "Dinner split",
  },
];
